# Generated by Django 5.0.1 on 2024-03-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsupplier',
            old_name='ruc',
            new_name='cuil',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='ruc',
            new_name='cuil',
        ),
    ]
